apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: psb-mq-sre
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-RJON-BN7PN3
    metric: ProcessorValueUnit
    use: NonProduction
  queueManager:
    availability:
      type: SingleInstance
    debug: false
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 90
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    logFormat: Basic
    metrics:
      enabled: true
    name: PSBMQSRE
    mqsc:
    - configMap:
        name: psb-mq-config
        items:
        - psb-mq-ace.mqsc
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    storage:
      persistedData:
        enabled: false
      queueManager:
        type: ephemeral
      recoveryLogs:
        enabled: false
  securityContext:
    initVolumeAsRoot: false
  template:
    pod:
      containers:
      - env:
        - name: MQSNOAUT
          value: "yes"
        name: qmgr
        resources: {}
  terminationGracePeriodSeconds: 30
  tracing:
    agent: {}
    collector: {}
    enabled: false
    namespace: ""
  version: 9.2.0.0-r1
  web:
    enabled: true
