apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dev-pipeline
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
  workspaces:
    - name: git-source
  tasks:
    - name: clone-git-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "{{FORKED_REPO}}"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "{{BRANCH}}"
      workspaces:
        - name: output
          workspace: git-source


    # MQ deploy in dev namespace
    - name: deploy-mq
      runAfter:
        - clone-git-source
      taskRef:
        name: deploy-task
      params:
        - name: imageTag
          value: "latest"
        - name: imageName
          value: "na"
        - name: releaseName
          value: "na"
        - name: releaseScript
          value: release-psb-mq.sh
        - name: namespace
          value: "{{NAMESPACE}}"
      workspaces:
        - name: git-source
          workspace: git-source

    # build ace in dev namespace
    - name: build-ace-sre
      runAfter:
        - deploy-mq
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ace-api"
        - name: dockerfile
          value: "ACE-SRE.Dockerfile"
        - name: contextPath
          value: "Bar_files/ace-sre"
        - name: pvc
          value: "buildah-ace-sre"
      workspaces:
        - name: git-source
          workspace: git-source

    # deploy ace sre in dev namespace
    - name: deploy-wait-ace-sre
      runAfter:
        - build-ace-sre
      taskRef:
        name: deploy-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ace-sre"
        - name: releaseName
          value: "ace-sre-rsrv"
        - name: releaseScript
          value: release-ace-integration-server.sh
        - name: namespace
          value: "{{NAMESPACE}}"
      workspaces:
        - name: git-source
          workspace: git-source