apiVersion: v1
kind: Secret
metadata:
  name: default-mail-server-creds
type: Opaque
stringData:
  default-mail-server-creds.yaml: |-
    mail_servers:
      - name: default-mail-server
        credentials:
          username: "{{{ mail_server_username }}}"
          password: "{{{ mail_server_password }}}"
