apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: apic-configurator
  name: apic-configurator
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: apic-configurator
    spec:
      serviceAccountName: apic-configurator-sa
      restartPolicy: Never
      containers:
        - name: configurator
          image: {{{ configurator_image }}}
          volumeMounts:
            - name: configs
              mountPath: /app/configs
      volumes:
        - name: configs
          projected:
            sources:
            - configMap:
                name: configurator-base
                items:
                  - key: configurator-base.yaml
                    path: overrides/configurator-base.yaml
            - secret:
                name: default-mail-server-creds
                items:
                  - key: default-mail-server-creds.yaml
                    path: overrides/default-mail-server-creds.yaml
