apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apic-configurator-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apic-configurator-rolebinding
subjects:
- kind: ServiceAccount
  name: apic-configurator-sa
  namespace: {{{ apim_namespace }}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apic-configurator-role